[program:octane]
command=php /var/www/artisan octane:start --workers=8 --host=0.0.0.0 --port=8000
directory=/var/www
autostart=true
autorestart=true
user=root
numprocs=1
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stopwaitsecs=3600
startsecs=2
priority=999
